name: "apple0" # name of group in wandb
project: "actsrf"
dataset_dir: "/mnt/hdd8/Datasets/nerf-sos-datasets/co3d_colmap/co3d_apple_110_13051_23361"
store_result: # where to store results
  semantic_ngp: "/mnt/hdd8/skorokhodov_vs/results/semantic_ngp_results/"
  torch_ngp: "/mnt/hdd8/skorokhodov_vs/results/torch-ngp_results"
  semantic_nerf: "/mnt/hdd8/skorokhodov_vs/results/semantic_nerf_results"
start: # start script
  semantic_ngp: "/home/skorokhodov_vs/nerf/from_laba/ngp_with_semantic_nerf/main_nerf.py"
  torch_ngp: "/home/skorokhodov_vs/nerf/from_laba/torch-ngp/main_nerf.py"
  semantic_nerf: "/home/skorokhodov_vs/nerf/from_laba/semantic_nerf/train_SSR_main_time_measure.py"

convert_script_path: "/home/skorokhodov_vs/nerf/from_laba/ngp_with_semantic_nerf/scripts/llff2nerf.py" # script to convert poses to nerf format
split_script_path: "/home/skorokhodov_vs/nerf/from_laba/ngp_with_semantic_nerf/scripts/make_split.py"
continue_on_fail: True
gpu: [2]

experiments:
### EXPERIMENT 1 ###
  -
    w: 640
    h: 480
    place: ""
    sequence: ""
    need_transforms: True
    
    # total: 202 photos
    eval_ratio: 0.125   # 25
    train_ratio: 0.625  # 126
    holdout_ratio: 0.0  # 0
    test_ratio: 0.250   # 50

    common: 
      epochs: 100

      downscale: 2
      video_mode: 2
      lr: 0.003
      bound: 5.0
      scale: 0.5
      max_ray_batch: 2048
      use_uncert: True
      use_semantic: True
      use_semantic_uncert: True
      # parameters for active learning
      active_learning_interval: 1550
      active_learning_num: 10

    semantic_ngp:
      -
        omega: 0.3
        lambd: 0.25
        resume: True
        do_run: True
