name: "many-gpu-03-05-2023" # name of group in wandb
project: "ngp_with_semantic_nerf"
place_names: ["room_0", "room_1", "room_2", "office_0", "office_1", "office_2", "office_3", "office_4"]
sequences: ["Sequence_1", "Sequence_2"]
scene_dir: "/mnt/hdd8/Datasets/Replica/semantic_info/"
dataset_dir: "/mnt/hdd8/Datasets/Replica/"
store_result: # where to store results
  semantic_ngp: "/mnt/hdd8/skorokhodov_vs/results/semantic_ngp_results/"
  torch_ngp: "/mnt/hdd8/skorokhodov_vs/results/torch-ngp_results"
  semantic_nerf: "/mnt/hdd8/skorokhodov_vs/results/semantic_nerf_results"
start: # start script
  semantic_ngp: "/home/skorokhodov_vs/nerf/from_laba/ngp_with_semantic_nerf/main_nerf.py"
  torch_ngp: "/home/skorokhodov_vs/nerf/from_laba/torch-ngp/main_nerf.py"
  semantic_nerf: "/home/skorokhodov_vs/nerf/from_laba/semantic_nerf/train_SSR_main_time_measure.py"

convert_script_path: "/home/skorokhodov_vs/nerf/replica2nerf.py" # script to convert poses to nerf format
continue_on_fail: False
gpu: [0, 2]

experiments:
### EXPERIMENT 1 ###
  -
    w: 640
    h: 480
    place: "room_1"
    sequence: "Sequence_1"
    need_transforms: False

    semantic_ngp:
      - 
        name: "1"
        
        epochs: 2
        max_ray_batch: 4096
        num_rays: 1024
        num_steps: 512
        
        save_interval: 2
        eval_interval: 2
        active_learning_interval: 2
        video_interval: 2

        eval_ratio: 0.01
        train_ratio: 0.01
        holdout_ratio: 0.01
        video_mode: 2

        lambd: 0.01
        omega: 0.0
        n_test: 10

      - 
        name: "2"
        
        epochs: 2
        max_ray_batch: 4096
        num_rays: 1024
        num_steps: 512
        
        save_interval: 2
        eval_interval: 2
        active_learning_interval: 2
        video_interval: 2

        eval_ratio: 0.01
        train_ratio: 0.01
        holdout_ratio: 0.01
        video_mode: 2
        use_semantic: True

        lambd: 0.01
        omega: 0.0
        n_test: 10

      - 
        name: "3"
        
        epochs: 2
        max_ray_batch: 4096
        num_rays: 1024
        num_steps: 512
        
        save_interval: 2
        eval_interval: 2
        active_learning_interval: 2
        video_interval: 2

        eval_ratio: 0.01
        train_ratio: 0.01
        holdout_ratio: 0.01
        video_mode: 2
        use_semantic: True
        use_uncert: True

        lambd: 0.01
        omega: 0.0
        n_test: 10

      - 
        name: "4"
        
        epochs: 2
        max_ray_batch: 4096
        num_rays: 1024
        num_steps: 512
        
        save_interval: 2
        eval_interval: 2
        active_learning_interval: 2
        video_interval: 2

        eval_ratio: 0.01
        train_ratio: 0.01
        holdout_ratio: 0.01
        video_mode: 2
        use_uncert: True
        use_semantic_uncert: True

        lambd: 0.01
        omega: 0.0
        n_test: 10
        su_weight: 0.5

      - 
        name: "5"
        
        epochs: 2
        max_ray_batch: 4096
        num_rays: 1024
        num_steps: 512
        
        save_interval: 2
        eval_interval: 2
        active_learning_interval: 2
        video_interval: 2

        eval_ratio: 0.01
        train_ratio: 0.01
        holdout_ratio: 0.01
        video_mode: 2
        use_uncert: True
        use_semantic_uncert: True

        lambd: 0.01
        omega: 0.0
        n_test: 10
