name: "uncertainty-26-04-2023" # name of group in wandb
place_names: ["room_0", "room_1", "room_2", "office_0", "office_1", "office_2", "office_3", "office_4"]
sequences: ["Sequence_1", "Sequence_2"]
scene_dir: ""
dataset_dir: "/mnt/hdd8/Datasets/lego/"
store_result: # where to store results
  semantic_ngp: "/mnt/hdd8/skorokhodov_vs/results/semantic_ngp_results/"
  torch_ngp: "/mnt/hdd8/skorokhodov_vs/results/torch-ngp_results"
  semantic_nerf: "/mnt/hdd8/skorokhodov_vs/results/semantic_nerf_results"
start: # start script
  semantic_ngp: "/home/skorokhodov_vs/nerf/from_laba/ngp_with_semantic_nerf/main_nerf.py"
  torch_ngp: "/home/skorokhodov_vs/nerf/from_laba/torch-ngp/main_nerf.py"
  semantic_nerf: "/home/skorokhodov_vs/nerf/from_laba/semantic_nerf/train_SSR_main_time_measure.py"

convert_script_path: "/home/skorokhodov_vs/nerf/lego2nerf.py" # script to convert poses to nerf format
continue_on_fail: False
gpu: 0

experiments:
### EXPERIMENT 1 ###
  -
      w: 800
      h: 800
      place: ""
      sequence: ""
      need_transforms: False

      semantic_ngp:
        - 
          name: "lego1"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          lambd: 0.01
          omega: 0.3
          not_use_semantic: True
          save_interval: 50
          eval_interval: 25
          do_run: False

        - 
          name: "lego1.1"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.9
          lambd: 0.01
          omega: 0.3
          not_use_semantic: True
          save_interval: 50
          eval_interval: 50
          resume: True
          do_run: False

        - 
          name: "lego2"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          eval_interval: 50
          save_interval: 50
          lambd: 0.01
          omega: 0.5
          not_use_semantic: True
          do_run: False

        - 
          name: "lego3"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          lambd: 0.01
          omega: 0.7
          not_use_semantic: True
          save_interval: 50
          eval_interval: 50
          do_run: False

        - 
          name: "lego4"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          eval_interval: 50
          save_interval: 50
          lambd: 0.01
          omega: 0.1
          not_use_semantic: True
          do_run: False

        - 
          name: "lego5"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          eval_interval: 50
          save_interval: 50
          lambd: 0.01
          omega: 0.05
          not_use_semantic: True
          do_run: False

      torch_ngp:
        - 
          name: "lego6"
          epochs: 300
          max_ray_batch: 2048
          num_rays: 1024
          num_steps: 512
          eval_ratio: 0.8
          save_interval: 50
          eval_interval: 50
          do_run: False